const companies={dewu:{name:'得物',role:'家电商品运营实习生',time:'2026.02 — 2026.06 · 上海',overview:'围绕家电商品供给质量、信息展示与发布效率，参与数据分析、治理策略制定及跨团队方案推进。',projects:[['商品供给治理','商品信息存在薄弱项与供给缺口，需要从数据中定位治理方向。','从标题、主图、详情页、价格等维度拆解商品信息分，结合销量、GMV、上架数周报定位问题；联动外包团队推动商家信息、出价与上架治理。','家电高优商品占比提升至 99.26%。'],['新品标签推荐逻辑优化','家电新品信息呈现不足，新品心智尚未建立。','独立撰写新品标签需求文档，以上架 90 天内自动识别为新品为判定逻辑，推动标签在关联浮层、多色小图等场景上线。','新品点击率提升约 16.8%。'],['多规格商品展示优化','详情页仅展示首层规格，增加了用户选购理解成本。','梳理商品规格层级，产出按 SKU 配置商品图的展示方案，协调打通前后端数据与展示逻辑。','方案覆盖家电全量在架商品 6W+，提升商品信息展示完整度与选购效率。'],['AI 生图链路迭代','生活服务类目图片供给不足、规范不统一，个人卖家发布商品存在图片制作门槛。','梳理各品类生图需求与模板规则，跟进 AI 自动生图链路迭代；结合图片审核机制优化，推动能力迁移至个人卖家轻量化发布链路。','个人卖家发品量月环比增长 50%；上架成功率提升 78%；节约做图成本 10W+。']]},ctrip:{name:'携程',role:'海外租车业务运营实习生',time:'2025.09 — 2025.12 · 上海',overview:'围绕海外租车保险业务，参与经营数据分析、差异化调价策略与服务流程优化。',projects:[['数据洞察与调价策略','需要结合各国、各供应商表现，寻找租车保险搭售与收益优化空间。','基于搭售率与单均毛利输出看板和问题归因；从价格、服务内容、理赔周期对比竞品，制定分国家、分供应商的差异化调价策略并推动落地测试。','搭售率提升 5%，总收益提升 3%。'],['保险规则标准化','日本供应商保险免赔额与承保范围规则不一致，影响用户理赔体验。','参与规则统一专项，汇总分析 149 家供应商反馈，提炼免赔额、理赔范围等共性问题并输出优化建议。','推动日本供应商保险规则标准化。'],['理赔体验优化','理赔材料补件频繁、理赔周期长，影响用户体验与复购。','拆解链路各环节痛点，设计理赔申请前置的新流程方案，减少客户参与节点，并将用户数据沉淀在平台侧。','理赔周期同比缩短 12%。'],['客服流程迭代','高频材料咨询与异常问题增加了客服沟通成本。','梳理 TOP 国家、TOP 车行理赔必备材料，产出标准模板，同步完善海外客服对客 SOP。','材料类异常咨询事件降低 26%，客服响应效率提升 35%。']]}};
const detail=document.querySelector('#detail'),lightbox=document.querySelector('#lightbox');
function openDialog(el){el.showModal();document.body.classList.add('modal-open')}
for(const dialog of document.querySelectorAll('dialog')){dialog.querySelector('.close').onclick=()=>dialog.close();dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});dialog.addEventListener('close',()=>document.body.classList.remove('modal-open'))}
document.querySelectorAll('[data-company]').forEach(button=>button.addEventListener('click',()=>{const c=companies[button.dataset.company];document.querySelector('#detail-content').innerHTML=`<span class="eyebrow">工作实践 / ${c.name}</span><h2>${c.name} · ${c.role}</h2><p>${c.time}</p><p>${c.overview}</p><div class="project-links">${c.projects.map((p,i)=>`<a href="#project-${i}">${p[0]}</a>`).join('')}</div>${c.projects.map((p,i)=>`<article class="project" id="project-${i}"><span class="eyebrow">0${i+1} / PROJECT</span><h3>${p[0]}</h3><h4>业务问题</h4><p>${p[1]}</p><h4>我的行动</h4><p>${p[2]}</p><h4>项目成果</h4><p class="result">${p[3]}</p></article>`).join('')}`;detail.querySelectorAll('.project-links a').forEach(a=>a.onclick=e=>{e.preventDefault();detail.querySelector(a.getAttribute('href')).scrollIntoView({behavior:'smooth',block:'start'})});openDialog(detail);detail.scrollTop=0}));
document.querySelectorAll('.origin').forEach(b=>b.addEventListener('pointerenter',e=>{const r=b.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;b.style.setProperty('--x',x+'px');b.style.setProperty('--y',y+'px');b.style.setProperty('--diameter',Math.ceil(2*Math.max(Math.hypot(x,y),Math.hypot(r.width-x,y),Math.hypot(x,r.height-y),Math.hypot(r.width-x,r.height-y)))+'px')}));
const photos=[['nara','Japan Nara','旅行'],['bali','Indonesia Bali','旅行'],['dog1','狗狗教！','日常'],['disney','Disney SH','旅行'],['dog2','狗狗教','日常'],['kobe','Kobe','旅行']];const carousel=document.querySelector('.carousel');let current=0,progress=0,startX=0,startProgress=0,lastX=0,lastTime=0,velocity=0,dragging=false,moved=false;
carousel.innerHTML=photos.map((p,i)=>`<button class="photo-card" aria-label="放大照片：${p[1]}" data-photo="${i}"><img src="assets/${p[0]}.jpg" alt="${p[1]}" draggable="false" loading="lazy"><span class="photo-badge">${p[2]}</span><span class="photo-title">${p[1]}</span></button>`).join('');const cards=[...carousel.children];
function render(){const mobile=innerWidth<650;cards.forEach((card,i)=>{let d=((i-progress)%6+6)%6;if(d>3)d-=6;card.style.transform=`translate(${d*(mobile?90:155)}px,${Math.abs(d)*(mobile?18:30)}px) rotate(${d*(mobile?8:11)}deg) scale(${1-Math.abs(d)*.1})`;card.style.zIndex=Math.round(100-Math.abs(d)*10);card.style.opacity=Math.abs(d)>2.8?0:1;card.querySelector('.photo-title').style.opacity=Math.abs(d)<.5?1:0;card.tabIndex=i===((current%6+6)%6)?0:-1});document.querySelector('#counter').textContent=(((current%6)+6)%6+1)+' / 6'}
function go(n){current=n;progress=n;render()}render();addEventListener('resize',render);document.querySelector('#prev').onclick=()=>go(current-1);document.querySelector('#next').onclick=()=>go(current+1);carousel.onkeydown=e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();go(current+(e.key==='ArrowRight'?1:-1))}};
carousel.addEventListener('pointerdown',e=>{if(e.button!==0)return;dragging=true;moved=false;startX=lastX=e.clientX;startProgress=progress;lastTime=performance.now();velocity=0;carousel.classList.add('dragging')});addEventListener('pointermove',e=>{if(!dragging)return;const now=performance.now();velocity=(e.clientX-lastX)/Math.max(1,now-lastTime);lastX=e.clientX;lastTime=now;if(Math.abs(e.clientX-startX)>6)moved=true;progress=startProgress-(e.clientX-startX)/(innerWidth<650?180:250);render()});function end(){if(!dragging)return;dragging=false;carousel.classList.remove('dragging');let shift=Math.round((startX-lastX)/(innerWidth<650?120:200)-velocity*.3);shift=Math.max(-3,Math.min(3,shift));go(Math.round(startProgress)+shift)}addEventListener('pointerup',end);addEventListener('pointercancel',()=>{end();moved=true});cards.forEach((c,i)=>c.onclick=()=>{if(moved)return;if(i!==((current%6+6)%6)){go(current+Number((((i-current)%6)+9)%6-3));return}lightbox.querySelector('img').src=`assets/${photos[i][0]}.jpg`;lightbox.querySelector('img').alt=photos[i][1];lightbox.querySelector('p').textContent=photos[i][1];openDialog(lightbox)});
document.querySelector('#copy').onclick=async()=>{try{await navigator.clipboard.writeText('dijiayang1012@outlook.com');document.querySelector('#copy-status').textContent='邮箱已复制';document.querySelector('#copy').textContent='已复制 ✓'}catch{document.querySelector('#copy-status').textContent='请长按或选中上方邮箱复制。'}};
const observer=new IntersectionObserver(entries=>{for(const e of entries)if(e.isIntersecting){document.querySelectorAll('nav a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+e.target.id))}},{rootMargin:'-15% 0px -55% 0px',threshold:0});document.querySelectorAll('main>section[id]').forEach(s=>observer.observe(s));
const campusDetails=document.querySelector('.campus-detail');campusDetails.addEventListener('toggle',()=>{campusDetails.querySelector('.expand').textContent=campusDetails.open?'收起 −':'展开 +'});
